- name: Install docker-compose 
  pip:
    name: 
    - requests==2.31.0
    - docker<7.0
    - docker-compose

- name: Checkout Git Repo
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"

- name: Start docker-compose up
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes